### ISSUE TITLE
more config

### ISSUE THREAD

**Issue by 416207298** [arnamak/stay-centered.nvim#6]
Is there any way to disable stay-centered just under certain circumstances, such as: in tagbar.

**Comment by arnamak** [comment]
@416207298 not sure I understand the example, could you clarify what you mean by tagbar?

There's an option to disable it for certain filetypes, so if there's a filetype for what you're referring to--you can disable it that way.

[Towards the bottom of the README](https://github.com/arnamak/stay-centered.nvim#example)

**Comment by arnamak** [comment]
I'm going to close this issue as stale, if you have some clarifying info or would like to re-open--feel free to do so!

**Comment by 416207298** [comment]
Sorry for this late reply. Tagbar is a plugin for nvim which is used for show functions and defines on the right/left side. And stay-centered is not quite good when cursor is in tagbar window. That's why I want to disable it.

**Comment by arnamak** [comment]
@416207298 No worries, I believe you should be able to do this now as of this change that was merged last week: https://github.com/arnamak/stay-centered.nvim/pull/11
